# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'

    session:
        enabled: true
        cookie_secure: auto
        cookie_samesite: lax

    default_locale: 'fr'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks: ['en']

    # allow locale switching via URL
    router:
        strict_requirements: true
        utf8: true
