applications:
  d-symfony:
    source:
      root: "."          # current directory

    type: "php:8.4"

    web:
      locations:
        "/":
          passthru: "/index.php"
          root: "public"

    variables:
      env:
        N_PREFIX: "/app/.global"

    build:
      flavor: none

    dependencies:
      nodejs:
        n: "*"
        npx: "*"
      php:
        composer/composer: "^2"

    hooks:
      build: |
        set -eux
        composer --no-ansi --no-interaction install --no-progress --prefer-dist --optimize-autoloader --no-dev
        n auto || n lts
        hash -r
        npm i
      deploy: |
        set -eux
        # echo 'Put your deploy commands here'

routes:
  "https://{default}/":
    type: upstream
    upstream: "d-symfony:http"
  "https://www.{default}":
    type: redirect
    to: "https://{default}/"
